-- Fix body_conditions self-reference constraint to allow cascading deletes
-- previous_observation_id prevents deleting rows if they are referenced by other rows
-- unless we set ON DELETE SET NULL or CASCADE

BEGIN;

-- 1. Drop the existing constraint
-- We need to find the name first, or we can assume the standard naming convention if generated by Supabase/Postgres
-- Usually: table_column_fkey
ALTER TABLE public.body_conditions
DROP CONSTRAINT IF EXISTS body_conditions_previous_observation_id_fkey;

-- 2. Re-add the constraint with ON DELETE SET NULL
ALTER TABLE public.body_conditions
ADD CONSTRAINT body_conditions_previous_observation_id_fkey
FOREIGN KEY (previous_observation_id)
REFERENCES public.body_conditions(id)
ON DELETE SET NULL;

COMMIT;
